### ISSUE TITLE
error: Illegal colon character in JDK path

### ISSUE THREAD

**Issue by Felk** [alkimiapps/gradle-dplink-plugin#3]
Hello,

when I try to run `gradle dplink` I get an error.

- Windows 10 64-bit
- gradle 4.7
- Executed in Powershell
- plugin version 0.3

Here's the error:

```
PS D:\Projekte\git\Game-12> gradle dplink --stacktrace --info
Initialized native services in: C:\Users\felk\.gradle\native
The client will now receive all logging from the daemon (pid: 7604). The daemon log file: C:\Users\felk\.gradle\daemon\4.7\daemon-7604.out.log
Starting 2nd build in daemon [uptime: 34.601 secs, performance: 100%, no major garbage collections]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file 'D:\Projekte\git\Game-12\settings.gradle'.
Projects loaded. Root project using build file 'D:\Projekte\git\Game-12\build.gradle'.
Included projects: [root project 'game-12', project ':annotations', project ':noise-engine']

> Configure project :
Evaluating root project 'game-12' using build file 'D:\Projekte\git\Game-12\build.gradle'.

> Configure project :annotations
Evaluating project ':annotations' using build file 'D:\Projekte\git\Game-12\annotations\build.gradle'.

> Configure project :noise-engine
Evaluating project ':noise-engine' using build file 'D:\Projekte\git\NoiseEngine\build.gradle'.
All projects evaluated.
Selected primary task 'dplink' from project :
Tasks to be executed: [GradleDplinkTask(javaHome=, modulesHome=, outputDir=, executableJar=, mainClassName=, jvmArgs=, appArgs=, appName=, allJavaModules=false, fatJar=false, verbose=false)]
:dplink (Thread[Daemon worker,5,main]) started.

> Task :dplink FAILED
Task ':dplink' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Error: Illegal char <:> at index 38: C:\Program Files\Java\jdk-10.0.1/jmods:mlib
:dplink (Thread[Daemon worker,5,main]) completed. Took 1.464 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for GradleDplinkTask(javaHome=, modulesHome=, outputDir=, executableJar=, mainClassName=, jvmArgs=, appArgs=, appName=, allJavaModules=false, fatJar=false, verbose=false).
> Command failed with exit code 1: C:\Program Files\Java\jdk-10.0.1\bin\jlink --module-path C:\Program Files\Java\jdk-10.0.1/jmods:mlib --add-modules java.desktop,java.compiler,jdk.unsupported,java.base --output D:\Projekte\git\Game-12\build\app --no-header-files --no-man-pages --compress=2

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for GradleDplinkTask(javaHome=, modulesHome=, outputDir=, executableJar=, mainClassName=, jvmArgs=, appArgs=, appName=, allJavaModules=false, fatJar=false, verbose=false).
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at <no one cares>
Caused by: java.lang.RuntimeException: Command failed with exit code 1: C:\Program Files\Java\jdk-10.0.1\bin\jlink --module-path C:\Program Files\Java\jdk-10.0.1/jmods:mlib --add-modules java.desktop,java.compiler,jdk.unsupported,java.base --output D:\Projekte\git\Game-12\build\app --no-header-files --no-man-pages --compress=2
        at com.alkimiapps.gradle.plugin.dplink.internal.DplinkExecutor.lambda$execCommand$11(DplinkExecutor.java:252)
        at com.alkimiapps.javatools.Sugar.fatalGuard(Sugar.java:21)
        at com.alkimiapps.gradle.plugin.dplink.internal.DplinkExecutor.execCommand(DplinkExecutor.java:248)
        at <no one cares>
```

**Comment by alkimiapps** [comment]
Hello @Felk . Thanks for raising this issue. I'm afraid that dplink has not yet been set up to work on Windows/MSDOS. I've only tested on unix style platforms so far. This particular issue seems to be due to the use of a unix style path separator in DplinkExecutor.jlink line 149. But there are other unix path separators hardcoded also that would break later in the process on Windows/MSDOS.

It would be good to get it working on Window/MSDOS too.

**Comment by Felk** [comment]
My workaround is to run it in the Windows 10 Linux Bash. I get "BUILD SUCCESSFUL", but an empty "build/libs" directory, probably because I don't know how to set up java 9 modules though

**Comment by calvertdw** [comment]
Looks like it just needs to be a `;` after reading https://docs.oracle.com/javase/9/tools/jlink.htm#JSWOR-GUID-CECAC52B-CFEE-46CB-8166-F17A8E9280E9

Running the following command manually worked for me:
` C:\jdk-11.0.2\bin\jlink --module-path C:\jdk-11.0.2\jmods;mlib --add-modules java.base --output C:\dev\gradle-java9-kotlin\java-only\build\app --no-header-files --no-man-pages --compress=2`
